import {describe,expect,it} from "vitest";
import {createDiagramScene} from "../src/index.js";
import {geometry,model} from "./fixtures.js";
describe("diagram scene",()=>{
 it("represents every entity with semantic identity and external geometry",()=>{const result=createDiagramScene({model,geometry});expect(result.ok).toBe(true);if(!result.ok)return;expect(result.scene.status).toBe("ready");expect(result.scene.entities).toHaveLength(5);expect(result.scene.entities.find(e=>e.identity.value==="api")).toMatchObject({kind:"element",geometry:geometry.entities.api,identity:{kind:"element",value:"api"}});expect(result.scene.textAlternative).toContain("api");expect(result.scene.textAlternative).toContain("api → db")});
 it("truncates long Unicode labels predictably while preserving accessible text",()=>{const result=createDiagramScene({model,geometry,maxLabelLength:18});expect(result.ok).toBe(true);if(!result.ok)return;const api=result.scene.entities.find(e=>e.identity.value==="api")!;expect(Array.from(api.label)).toHaveLength(18);expect(api.label.endsWith("…")).toBe(true);expect(api.ariaLabel).toContain(api.fullLabel)});
 it("distinguishes selection, focus and errors without relying only on color",()=>{const result=createDiagramScene({model,geometry,state:{selectedId:"api",focusedId:"db",errorIds:["writes"]}});expect(result.ok).toBe(true);if(!result.ok)return;expect(result.scene.entities.find(e=>e.identity.value==="api")).toMatchObject({state:"selected",stateLabel:"Selecionado"});expect(result.scene.entities.find(e=>e.identity.value==="db")).toMatchObject({state:"focused",stateLabel:"Em foco"});expect(result.scene.entities.find(e=>e.identity.value==="writes")).toMatchObject({state:"error",stateLabel:"Com erro"})});
 it("returns unavailable or empty scenes explicitly",()=>{const unavailable=createDiagramScene({model,geometry,validation:{diagnostics:[{code:"SEMANTIC_MISSING_FIELD",severity:"error",message:"Erro",range:model.provenance.range,related:[]}],hasErrors:true,canProceed:false}});expect(unavailable).toMatchObject({ok:true,scene:{status:"unavailable",entities:[]}});expect(createDiagramScene({model:null,geometry:{entities:{}}})).toMatchObject({ok:true,scene:{status:"empty",entities:[]}})});
 it("rejects absent geometry and unknown interaction identities",()=>{expect(createDiagramScene({model,geometry:{entities:{}}})).toMatchObject({ok:false,errors:[{code:"MISSING_GEOMETRY",entityId:"api"}]});expect(createDiagramScene({model,geometry,state:{selectedId:"missing"}})).toMatchObject({ok:false,errors:[{code:"INVALID_RENDER_STATE",entityId:"missing"}]})});
});
