import { emptyPlacementState, expandContainerToFit, findAlignmentGuides, MIN_ELEMENT_HEIGHT, MIN_ELEMENT_WIDTH, moveElement, resizeElement, setPinned, snapPoint, type AlignmentGuide, type Box } from '@adl/canvas-state'
import { calculateLayout, type LayoutResult } from '@adl/layout'
import { parse } from '@adl/parser'
import { createDiagramScene, createExportScene, type EntityView } from '@adl/renderer'
import { buildSemanticModel, type DiagramModel } from '@adl/semantic'
import { serializeModel } from '@adl/serializer'
import { WorkspaceRepository, type PersistedWorkspaceEnvelope } from '@adl/persistence'
import { updateElementRule, type Paint, type ResolvedDiagramStyles, type ResolvedElementStyle, type TextStyle } from '@adl/stylesheet'
import { useCallback, useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { createSourceBinding } from './features/code-editor/source-binding.js'
import { LazyEditorTabs as EditorTabs } from './features/code-editor/LazyEditorTabs.js'
import { runStylesheetPipeline } from './features/stylesheet/stylesheet-pipeline.js'
import { AssistantConversation, CanvasToolbar, TopBar } from './features/workspace/WorkspaceChrome.js'
import { useAssistance } from './features/assistant/use-assistance.js'
import { createExport, downloadArtifact } from './features/export/export-service.js'
import { NewDiagramDialog } from './features/workspace/NewDiagramDialog.js'
import { paymentExampleAdl, paymentExampleAdls } from './features/workspace/payment-example.js'
import { WorkspaceController, type WorkspaceSnapshot } from './features/workspace/workspace-controller.js'
import { defaultPreferences } from './features/workspace/workspace-preferences.js'
import { createWorkspaceStore } from './features/workspace/workspace-store.js'
import { AlignmentGuides } from './features/canvas/AlignmentGuides.js'
import { MobileDrawer } from './features/workspace/MobileDrawer.js'
import { InlineLabelEditor } from './features/canvas/InlineLabelEditor.js'
import { ContextMenu } from './features/canvas/ContextMenu.js'
import { BrowserStorageAdapter } from './features/persistence/browser-storage-adapter.js'
import './source-tabs.css'


export const source = paymentExampleAdl
const appliedStylesheet=paymentExampleAdls
const parsed = parse(source)
if (!parsed.ok) throw new Error('Invalid fixture')
const semantic = buildSemanticModel(parsed.document)
if (!semantic.ok) throw new Error('Invalid model')
const model = semantic.model
type BoxEntity = Exclude<EntityView,{kind:'relation'}>
const center = (entity: BoxEntity) => ({ x: entity.geometry.x + entity.geometry.width / 2, y: entity.geometry.y + entity.geometry.height / 2 })
const boundaryPoint=(from:BoxEntity,to:BoxEntity)=>{const a=center(from),b=center(to),dx=b.x-a.x,dy=b.y-a.y;if(dx===0&&dy===0)return a;const scale=.5/Math.max(Math.abs(dx)/from.geometry.width,Math.abs(dy)/from.geometry.height);return{x:a.x+dx*scale,y:a.y+dy*scale}}
const relationMarkers=(kind:Extract<EntityView,{kind:'relation'}>['connectorKind'])=>({markerStart:kind==='always-link'?'url(#mdl-circle)':undefined,markerEnd:kind==='specialization'?'url(#mdl-specialization)':kind==='composition'?'url(#mdl-composition)':'url(#mdl-arrow)'})
type ResizeCorner = 'nw' | 'ne' | 'sw' | 'se'
type ResizeGesture = { readonly id: string; readonly corner: ResizeCorner; readonly clientX: number; readonly clientY: number; readonly box: Box }
const resizeHandles = [{ corner: 'nw', x: 0, y: 0, label: 'superior esquerdo' }, { corner: 'ne', x: 1, y: 0, label: 'superior direito' }, { corner: 'sw', x: 0, y: 1, label: 'inferior esquerdo' }, { corner: 'se', x: 1, y: 1, label: 'inferior direito' }] as const
const paintValue=(paint:Paint|undefined,fallback:string)=>paint?.kind==='solid'?paint.color:fallback
const textAttributes=(style:TextStyle|undefined)=>{if(!style)return{};const textAnchor:'start'|'end'|'middle'=style.textAlign==='left'?'start':style.textAlign==='right'?'end':'middle';return{fill:paintValue(style.paint,'currentColor'),fontSize:style.fontSize,fontFamily:style.fontFamily.join(', '),fontWeight:style.fontWeight,fontStyle:style.fontStyle,textDecoration:style.textDecoration,textAnchor}}
function ElementShape({geometry,style}:{readonly geometry:Box;readonly style?:ResolvedElementStyle}){const common={fill:paintValue(style?.fill,'#10151c'),stroke:paintValue(style?.borderPaint,'#3a4655'),strokeWidth:style?.borderWidth??1,transform:style?.rotation?`rotate(${style.rotation} ${geometry.x+geometry.width/2} ${geometry.y+geometry.height/2})`:undefined};if(style?.shape==='ellipse')return <ellipse className="element" data-shape="ellipse" cx={geometry.x+geometry.width/2} cy={geometry.y+geometry.height/2} rx={geometry.width/2} ry={geometry.height/2} {...common}/>;if(style?.shape==='parallelogram'){const skew=Math.min(24,geometry.width/5);return <path className="element" data-shape="parallelogram" d={`M ${geometry.x+skew} ${geometry.y} H ${geometry.x+geometry.width} L ${geometry.x+geometry.width-skew} ${geometry.y+geometry.height} H ${geometry.x} Z`} {...common}/>};if(style?.shape==='cylinder'){if(style.orientation==='horizontal'){const cap=Math.min(18,geometry.width/4);return <path className="element" data-shape="cylinder" data-orientation="horizontal" d={`M ${geometry.x+cap} ${geometry.y} A ${cap} ${geometry.height/2} 0 0 0 ${geometry.x+cap} ${geometry.y+geometry.height} H ${geometry.x+geometry.width-cap} A ${cap} ${geometry.height/2} 0 0 0 ${geometry.x+geometry.width-cap} ${geometry.y} Z M ${geometry.x+cap} ${geometry.y} A ${cap} ${geometry.height/2} 0 0 1 ${geometry.x+cap} ${geometry.y+geometry.height}`} {...common}/>};const cap=Math.min(18,geometry.height/4);return <path className="element" data-shape="cylinder" data-orientation="vertical" d={`M ${geometry.x} ${geometry.y+cap} A ${geometry.width/2} ${cap} 0 0 1 ${geometry.x+geometry.width} ${geometry.y+cap} V ${geometry.y+geometry.height-cap} A ${geometry.width/2} ${cap} 0 0 1 ${geometry.x} ${geometry.y+geometry.height-cap} Z M ${geometry.x} ${geometry.y+cap} A ${geometry.width/2} ${cap} 0 0 0 ${geometry.x+geometry.width} ${geometry.y+cap}`} {...common}/>};if(style?.shape==='user'){const radius=Math.min(18,geometry.height/5),cx=geometry.x+geometry.width/2;return <path className="element" data-shape="user" d={`M ${cx-radius} ${geometry.y+radius} A ${radius} ${radius} 0 1 0 ${cx+radius} ${geometry.y+radius} A ${radius} ${radius} 0 1 0 ${cx-radius} ${geometry.y+radius} M ${geometry.x+geometry.width*.2} ${geometry.y+geometry.height} Q ${geometry.x+geometry.width*.2} ${geometry.y+radius*2.5} ${cx} ${geometry.y+radius*2.5} Q ${geometry.x+geometry.width*.8} ${geometry.y+radius*2.5} ${geometry.x+geometry.width*.8} ${geometry.y+geometry.height} Z`} {...common}/>};return <rect className="element" data-shape="rectangle" {...geometry} rx={style?.borderRadius} {...common}/>}

function DiagramPreview({ model, styles, selectedIds=[], viewport={x:0,y:0,zoom:1}, onViewportChange, onSelectionChange, onModelChange, onElementGeometryChange, grid=true, snap=true, guides=true, gridSize=24, onTogglePreference }: { readonly model: DiagramModel; readonly styles?:ResolvedDiagramStyles; readonly selectedIds?:readonly string[];readonly viewport?:{readonly x:number;readonly y:number;readonly zoom:number};readonly onViewportChange?:(viewport:{x:number;y:number;zoom:number})=>void;readonly onSelectionChange?:(ids:readonly string[])=>void;readonly onModelChange?:(model:DiagramModel,type:'semantic.add-relation'|'semantic.update-element'|'semantic.remove-elements'|'semantic.duplicate-elements'|'semantic.update-relation'|'semantic.reverse-relation'|'semantic.remove-relation')=>void; readonly onElementGeometryChange?:(id:string,geometry:Box)=>void; readonly grid?:boolean;readonly snap?:boolean;readonly guides?:boolean;readonly gridSize?:number;readonly onTogglePreference?:(key:"grid"|"snap"|"guides")=>void }) {
  const [layout, setLayout] = useState<LayoutResult | null>(null)
  const selectedId=selectedIds.at(-1)??null
  const [editingId,setEditingId]=useState<string|null>(null)
  const [connectionStart,setConnectionStart]=useState<string|null>(null)
  const [contextMenu,setContextMenu]=useState<{kind:'canvas'|'element'|'relation';id?:string;x:number;y:number}|null>(null)
  const clipboardRef=useRef<readonly string[]>([])
  const touchPoints=useRef(new Map<number,{x:number;y:number}>())
  const pinchStart=useRef<{distance:number;zoom:number}|null>(null)
  const [placements, setPlacements] = useState(emptyPlacementState)
  const placementsRef=useRef(emptyPlacementState())
  const [drag, setDrag] = useState<{ readonly id: string; readonly clientX: number; readonly clientY: number; readonly x: number; readonly y: number } | null>(null)
  const [resize, setResize] = useState<ResizeGesture | null>(null)
  const [alignmentGuides,setAlignmentGuides]=useState<readonly AlignmentGuide[]>([])
  useEffect(() => { let active = true; const elementStyles=styles?Object.fromEntries(Object.entries(styles.elements).map(([id,style])=>[id,{width:style.width,height:style.height,rotation:style.rotation,...(style.position?{position:style.position}:{})}])):undefined;void calculateLayout(model,{elementStyles}).then(result => { if (active && result.ok) setLayout(result.layout) }); return () => { active = false } }, [model,styles])
  useEffect(()=>{const onKeyDown=(event:KeyboardEvent)=>{if(event.defaultPrevented)return;const target=event.target;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLElement&&target.isContentEditable)return;const delta=event.shiftKey?50:snap?gridSize:10,directions:Partial<Record<string,readonly[number,number]>>={ArrowLeft:[-delta,0],ArrowRight:[delta,0],ArrowUp:[0,-delta],ArrowDown:[0,delta]},direction=directions[event.key],id=selectedIds.at(-1);if(!direction||!id||!layout?.nodes[id]||!model.elements.some(item=>item.identity.value===id))return;event.preventDefault();const base=layout.nodes[id],placement=placementsRef.current.placements[id],current={x:placement?.x??base.x,y:placement?.y??base.y,width:placement?.width??base.width,height:placement?.height??base.height},point=snapPoint({x:current.x+direction[0],y:current.y+direction[1]},gridSize,snap),next=setPinned(moveElement(placementsRef.current,id,point,'keyboard'),id,true);placementsRef.current=next;setPlacements(next);onElementGeometryChange?.(id,{...current,...point})};addEventListener('keydown',onKeyDown);return()=>removeEventListener('keydown',onKeyDown)},[gridSize,layout,model.elements,onElementGeometryChange,selectedIds,snap])
  if (!layout) return <section className="preview" aria-label="Diagrama Payments Flow"><h2 className="sr-only">Diagrama</h2><p>Calculando layout…</p></section>
  const positionedNodes = Object.fromEntries(Object.entries(layout.nodes).map(([id, geometry]) => { const placement = placements.placements[id]; return [id, placement ? { ...geometry, x: placement.x, y: placement.y, width: placement.width ?? geometry.width, height: placement.height ?? geometry.height } : geometry] }))
  const result = createDiagramScene({ model, geometry: { entities: positionedNodes }, state: { selectedId }, styles })
  if (!result.ok) return <section className="preview" aria-label="Diagrama Payments Flow"><h2 className="sr-only">Diagrama</h2><p>Diagrama indisponível.</p></section>
  const elements = result.scene.entities.filter(entity => entity.kind === 'element'), groups = result.scene.entities.filter(entity => entity.kind === 'group'), relations = result.scene.entities.filter(entity => entity.kind === 'relation'), byId = new Map(elements.map(entity => [entity.identity.value, entity]))
  const focusableIds = [...groups, ...relations, ...elements].map(item => item.identity.value)
  const activeFocusableId = selectedId && focusableIds.includes(selectedId) ? selectedId : focusableIds[0]
  const rovingTabIndex = (id: string) => id === activeFocusableId ? 0 : -1
  const boxes = [...elements, ...groups], right = Math.max(...boxes.map(item => item.geometry.x + item.geometry.width), 650), bottom = Math.max(...boxes.map(item => item.geometry.y + item.geometry.height), 280)
  const updatePlacements=(updater:(current:typeof placements)=>typeof placements)=>setPlacements(current=>{const next=updater(current);placementsRef.current=next;return next})
  const place = (id: string, x: number, y: number, input: 'pointer' | 'keyboard') => {const point=snapPoint({x,y},gridSize,snap),element=elements.find(item=>item.identity.value===id);if(element&&guides)setAlignmentGuides(findAlignmentGuides({...element.geometry,...point},elements.filter(item=>item.identity.value!==id).map(item=>item.geometry)));updatePlacements(current => { let next=setPinned(moveElement(current,id,point,input),id,true);if(!element)return next;for(const group of groups.filter(item=>item.memberIds.includes(id)))next=expandContainerToFit(next,group.identity.value,group.geometry,{...element.geometry,...point});return next })}
  const commitGeometry=(id:string)=>{const placement=placementsRef.current.placements[id],base=layout.nodes[id];if(!placement||!base)return;onElementGeometryChange?.(id,{x:placement.x,y:placement.y,width:placement.width??base.width,height:placement.height??base.height})}
  const select=(id:string,additive=false)=>onSelectionChange?.(additive?(selectedIds.includes(id)?selectedIds.filter(item=>item!==id):[...selectedIds,id]):[id])
  const startDrag = (event: ReactPointerEvent<SVGGElement>, id: string, x: number, y: number) => { event.currentTarget.focus(); event.currentTarget.setPointerCapture(event.pointerId); select(id,event.ctrlKey||event.metaKey||event.shiftKey); setDrag({ id, clientX: event.clientX, clientY: event.clientY, x, y }) }
  const continueDrag = (event: ReactPointerEvent<SVGGElement>) => { if (!drag || drag.id !== event.currentTarget.dataset.entityId) return; const svg = event.currentTarget.ownerSVGElement; if (!svg) return; const bounds = svg.getBoundingClientRect(); const viewBox = svg.viewBox.baseVal; place(drag.id, drag.x + (event.clientX - drag.clientX) * viewBox.width / bounds.width, drag.y + (event.clientY - drag.clientY) * viewBox.height / bounds.height, 'pointer') }
  const startResize = (event: ReactPointerEvent<SVGRectElement>, element: EntityView, corner: ResizeCorner) => { if (element.kind === 'relation') return; event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); setResize({ id: element.identity.value, corner, clientX: event.clientX, clientY: event.clientY, box: element.geometry }) }
  const continueResize = (event: ReactPointerEvent<SVGRectElement>) => { if (!resize) return; event.stopPropagation(); const svg = event.currentTarget.ownerSVGElement; if (!svg) return; const bounds = svg.getBoundingClientRect(); const viewBox = svg.viewBox.baseVal; const dx = (event.clientX - resize.clientX) * viewBox.width / bounds.width, dy = (event.clientY - resize.clientY) * viewBox.height / bounds.height; const west = resize.corner.endsWith('w'), north = resize.corner.startsWith('n'); const width = Math.max(MIN_ELEMENT_WIDTH, resize.box.width + (west ? -dx : dx)), height = Math.max(MIN_ELEMENT_HEIGHT, resize.box.height + (north ? -dy : dy)); updatePlacements(current => resizeElement(current, resize.id, { x: west ? resize.box.x + resize.box.width - width : resize.box.x, y: north ? resize.box.y + resize.box.height - height : resize.box.y, width, height })) }
  const reorganize = () => void calculateLayout(model, { direction: 'DOWN' }, layout).then(next => { if (next.ok) setLayout(next.layout) })
  const rename=(id:string,value:string)=>{const elements=model.elements.map(item=>item.identity.value===id?{...item,name:value}:item),relations=model.relations.map(item=>item.identity.value===id?{...item,name:value}:item),groups=model.groups.map(item=>item.identity.value===id?{...item,name:value}:item);onModelChange?.({...model,elements,relations,groups},id in Object.fromEntries(model.relations.map(item=>[item.identity.value,true]))?'semantic.update-relation':'semantic.update-element');setEditingId(null)}
  const removeSelected=(selected:readonly string[]=selectedIds)=>{const ids=new Set(selected),elements=model.elements.filter(item=>!ids.has(item.identity.value)),elementIds=new Set(elements.map(item=>item.identity.value)),relations=model.relations.filter(item=>!ids.has(item.identity.value)&&elementIds.has(item.source.identity.value)&&elementIds.has(item.target.identity.value)),groups=model.groups.filter(item=>!ids.has(item.identity.value)).map(group=>({...group,members:group.members.filter(member=>elementIds.has(member.identity.value))}));onModelChange?.({...model,elements,relations,groups},selected.some(id=>model.relations.some(item=>item.identity.value===id))?'semantic.remove-relation':'semantic.remove-elements');onSelectionChange?.([])}
  const duplicateSelected=(ids:readonly string[]=selectedIds)=>{const taken=new Set([...model.elements,...model.relations,...model.groups].map(item=>item.identity.value)),copies=model.elements.filter(item=>ids.includes(item.identity.value)).map(item=>{let index=2,id=`${item.identity.value}-${index}`;while(taken.has(id))id=`${item.identity.value}-${++index}`;taken.add(id);return{...item,identity:{...item.identity,value:id},name:`${item.name} copy`}});if(copies.length){onModelChange?.({...model,elements:[...model.elements,...copies]},'semantic.duplicate-elements');onSelectionChange?.(copies.map(item=>item.identity.value))}}
  const finishConnection=(targetId:string)=>{if(!connectionStart||connectionStart===targetId){setConnectionStart(null);return}const source=model.elements.find(item=>item.identity.value===connectionStart),target=model.elements.find(item=>item.identity.value===targetId);if(!source||!target)return;const taken=new Set(model.relations.map(item=>item.identity.value));let index=1,id=`${connectionStart}-to-${targetId}`;while(taken.has(id))id=`${connectionStart}-to-${targetId}-${++index}`;onModelChange?.({...model,relations:[...model.relations,{identity:{kind:'relation',value:id},source:{identity:source.identity,provenance:source.provenance},target:{identity:target.identity,provenance:target.provenance},name:null,type:'link',description:null,properties:{},provenance:model.provenance}]},'semantic.add-relation');setConnectionStart(null)}
  const reverseRelation=(id:string)=>{const semantic=model.relations.find(item=>item.identity.value===id);if(semantic)onModelChange?.({...model,relations:model.relations.map(item=>item===semantic?{...item,source:item.target,target:item.source}:item)},'semantic.reverse-relation')}
  const contextAction=(action:string)=>{if(!contextMenu)return;const id=contextMenu.id;if(action==='Editar texto'&&id)setEditingId(id);if(action==='Duplicar'&&id)duplicateSelected([id]);if(action==='Excluir'&&id)removeSelected([id]);if(action==='Inverter direção'&&id)reverseRelation(id);if(action==='Colar')duplicateSelected(clipboardRef.current);if(action==='Ajustar à tela')reorganize();setContextMenu(null)}
  const updatePinch=()=>{const points=[...touchPoints.current.values()];if(points.length<2){pinchStart.current=null;return}const distance=Math.hypot(points[0]!.x-points[1]!.x,points[0]!.y-points[1]!.y);if(!pinchStart.current){pinchStart.current={distance,zoom:viewport.zoom};return}onViewportChange?.({...viewport,zoom:Math.min(2,Math.max(.25,pinchStart.current.zoom*distance/pinchStart.current.distance))})}
  return <section className={`preview ${grid?'':'grid-hidden'}`} aria-label="Diagrama Payments Flow" data-snap={snap} data-guides={guides} data-zoom={viewport.zoom.toFixed(2)} style={{backgroundSize:`${gridSize}px ${gridSize}px`}} onWheel={event=>{if(event.ctrlKey){event.preventDefault();onViewportChange?.({...viewport,zoom:Math.min(2,Math.max(.25,viewport.zoom*(event.deltaY>0?.9:1.1)))})}}} onContextMenu={event=>{event.preventDefault();setContextMenu({kind:'canvas',x:event.clientX,y:event.clientY})}} onPointerDown={event=>{if(event.pointerType==='touch'){touchPoints.current.set(event.pointerId,{x:event.clientX,y:event.clientY});updatePinch()}if(event.target===event.currentTarget)setContextMenu(null)}} onPointerMove={event=>{if(event.pointerType==='touch'&&touchPoints.current.has(event.pointerId)){touchPoints.current.set(event.pointerId,{x:event.clientX,y:event.clientY});updatePinch()}}} onPointerUp={event=>{touchPoints.current.delete(event.pointerId);updatePinch()}} onPointerCancel={event=>{touchPoints.current.delete(event.pointerId);updatePinch()}} onKeyDown={event=>{const target=event.target;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLElement&&target.isContentEditable)return;const shortcut=event.ctrlKey||event.metaKey;if((event.key==='Delete'||event.key==='Backspace')&&selectedIds.length){event.preventDefault();removeSelected()}if(shortcut&&event.key.toLowerCase()==='d'&&selectedIds.length){event.preventDefault();duplicateSelected()}if(shortcut&&event.key.toLowerCase()==='c'&&selectedIds.length){event.preventDefault();clipboardRef.current=selectedIds}if(shortcut&&event.key.toLowerCase()==='v'&&clipboardRef.current.length){event.preventDefault();duplicateSelected(clipboardRef.current)}}}><h2 className="sr-only">Diagrama</h2><div className="canvas-meta">Diagrama ADL · {elements.length} elementos</div>{guides&&<AlignmentGuides guides={alignmentGuides}/>}<svg className="diagram" viewBox={`${viewport.x} ${viewport.y} ${(right + 40)/viewport.zoom} ${(bottom + 40)/viewport.zoom}`} role="img" aria-label={result.scene.textAlternative}>
    <defs><marker id="mdl-arrow" markerWidth="10" markerHeight="10" refX="9" refY="5" orient="auto" markerUnits="strokeWidth"><path className="marker-chevron" d="M1 1 L9 5 L1 9"/></marker><marker id="mdl-circle" markerWidth="10" markerHeight="10" refX="5" refY="5" orient="auto" markerUnits="strokeWidth"><circle cx="5" cy="5" r="4"/></marker><marker id="mdl-specialization" markerWidth="12" markerHeight="12" refX="11" refY="6" orient="auto" markerUnits="strokeWidth"><path className="marker-outline" d="M0 0 L12 6 L0 12 Z"/></marker><marker id="mdl-composition" markerWidth="12" markerHeight="12" refX="11" refY="6" orient="auto" markerUnits="strokeWidth"><path d="M0 6 L6 0 L12 6 L6 12 Z"/></marker></defs>
    {groups.map(group => <g key={group.identity.value} role="button" tabIndex={rovingTabIndex(group.identity.value)} aria-label={`${group.ariaLabel}. Selecione para redimensionar.`} data-state={selectedIds.includes(group.identity.value)?'selected':group.state} onClick={event => select(group.identity.value,event.ctrlKey||event.metaKey||event.shiftKey)} onDoubleClick={()=>setEditingId(group.identity.value)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') select(group.identity.value,event.ctrlKey||event.metaKey||event.shiftKey) }}>
      <rect className="group" {...group.geometry}/>
      <text className="group-label" x={group.geometry.x+16} y={group.geometry.y+28}>{group.label}</text>{editingId===group.identity.value&&<foreignObject x={group.geometry.x+12} y={group.geometry.y+8} width={Math.max(120,group.geometry.width-24)} height={40}><InlineLabelEditor value={group.label} onCommit={value=>rename(group.identity.value,value)} onCancel={()=>setEditingId(null)}/></foreignObject>}
      {selectedId === group.identity.value && resizeHandles.map(handle => <rect key={handle.corner} className={`resize-handle resize-${handle.corner}`} role="slider" tabIndex={0} aria-label={`Redimensionar ${group.label} pelo canto ${handle.label}`} aria-valuemin={handle.x ? MIN_ELEMENT_WIDTH : MIN_ELEMENT_HEIGHT} aria-valuenow={handle.x ? group.geometry.width : group.geometry.height} x={group.geometry.x + handle.x * group.geometry.width - 6} y={group.geometry.y + handle.y * group.geometry.height - 6} width={12} height={12} onPointerDown={event => startResize(event, group, handle.corner)} onPointerMove={continueResize} onPointerUp={() => setResize(null)} onPointerCancel={() => setResize(null)}/>) }
    </g>)}
    {relations.map(relation => { const source=byId.get(relation.sourceId)!,target=byId.get(relation.targetId)!,a=boundaryPoint(source,target),b=boundaryPoint(target,source); return <g key={relation.identity.value} role="button" tabIndex={rovingTabIndex(relation.identity.value)} aria-label={`Conexão ${relation.label}`} aria-selected={selectedIds.includes(relation.identity.value)} data-state={selectedIds.includes(relation.identity.value)?'selected':relation.state} data-relation-id={relation.identity.value} data-connector-kind={relation.connectorKind} onClick={event=>select(relation.identity.value,event.ctrlKey||event.metaKey||event.shiftKey)} onContextMenu={event=>{event.preventDefault();event.stopPropagation();select(relation.identity.value);setContextMenu({kind:'relation',id:relation.identity.value,x:event.clientX,y:event.clientY})}} onDoubleClick={()=>setEditingId(relation.identity.value)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' ')select(relation.identity.value,event.ctrlKey||event.metaKey||event.shiftKey);if(event.key==='r')reverseRelation(relation.identity.value)}}><line className="relation-hit-target" x1={a.x} y1={a.y} x2={b.x} y2={b.y}/><line className={`relation relation-${relation.connectorKind}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={paintValue(relation.style?.linePaint,'#64748b')} strokeWidth={relation.style?.lineWidth} {...relationMarkers(relation.connectorKind)}/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-10} {...textAttributes(relation.style?.text)}>{relation.label}</text>{editingId===relation.identity.value&&<foreignObject x={(a.x+b.x)/2-80} y={(a.y+b.y)/2-35} width={160} height={40}><InlineLabelEditor value={relation.label} onCommit={value=>rename(relation.identity.value,value)} onCancel={()=>setEditingId(null)}/></foreignObject>}</g> })}
    {elements.map(element => <g key={element.identity.value} role="button" tabIndex={rovingTabIndex(element.identity.value)} aria-label={`${element.ariaLabel}. Arraste ou use as setas para mover.`} aria-selected={selectedIds.includes(element.identity.value)} data-entity-id={element.identity.value} data-state={selectedIds.includes(element.identity.value)?'selected':element.state} onPointerDown={event => startDrag(event, element.identity.value, element.geometry.x, element.geometry.y)} onPointerMove={continueDrag} onPointerUp={() => {if(connectionStart)finishConnection(element.identity.value);if(drag)commitGeometry(drag.id);setDrag(null);setAlignmentGuides([])}} onPointerCancel={() => {setDrag(null);setConnectionStart(null);setAlignmentGuides([])}} onContextMenu={event=>{event.preventDefault();event.stopPropagation();select(element.identity.value);setContextMenu({kind:'element',id:element.identity.value,x:event.clientX,y:event.clientY})}} onDoubleClick={()=>setEditingId(element.identity.value)} onKeyDown={event => { const delta = event.shiftKey ? 50 : snap ? gridSize : 10; const directions: Partial<Record<string, readonly [number, number]>> = { ArrowLeft: [-delta, 0], ArrowRight: [delta, 0], ArrowUp: [0, -delta], ArrowDown: [0, delta] }; const direction = directions[event.key]; if (direction) { event.preventDefault(); const x=element.geometry.x+direction[0],y=element.geometry.y+direction[1];place(element.identity.value,x,y,'keyboard');onElementGeometryChange?.(element.identity.value,{...element.geometry,...snapPoint({x,y},gridSize,snap)}) } else if (event.key === 'Enter' || event.key === ' ') select(element.identity.value,event.ctrlKey||event.metaKey||event.shiftKey) }}>
      <ElementShape geometry={element.geometry} style={element.style}/><text x={element.geometry.x+element.geometry.width/2} y={element.geometry.y+34} {...textAttributes(element.style?.text)}>{element.label}</text><text className="type" x={element.geometry.x+element.geometry.width/2} y={element.geometry.y+58} {...textAttributes(element.style?.text)}>{element.type}</text>{editingId===element.identity.value&&<foreignObject x={element.geometry.x+8} y={element.geometry.y+8} width={element.geometry.width-16} height={40}><InlineLabelEditor value={element.label} onCommit={value=>rename(element.identity.value,value)} onCancel={()=>setEditingId(null)}/></foreignObject>}
      {selectedIds.includes(element.identity.value)&&[{x:element.geometry.x,y:element.geometry.y+element.geometry.height/2,label:'esquerdo'},{x:element.geometry.x+element.geometry.width,y:element.geometry.y+element.geometry.height/2,label:'direito'},{x:element.geometry.x+element.geometry.width/2,y:element.geometry.y,label:'superior'},{x:element.geometry.x+element.geometry.width/2,y:element.geometry.y+element.geometry.height,label:'inferior'}].map(point=><circle key={point.label} className="connection-handle" role="button" aria-label={`Iniciar conexão pelo lado ${point.label}`} cx={point.x} cy={point.y} r={7} onPointerDown={event=>{event.stopPropagation();setConnectionStart(element.identity.value)}}/>)}
      {selectedId === element.identity.value && resizeHandles.map(handle => <rect key={handle.corner} className={`resize-handle resize-${handle.corner}`} role="slider" tabIndex={0} aria-label={`Redimensionar ${element.label} pelo canto ${handle.label}`} aria-valuemin={handle.x ? MIN_ELEMENT_WIDTH : MIN_ELEMENT_HEIGHT} aria-valuenow={handle.x ? element.geometry.width : element.geometry.height} x={element.geometry.x + handle.x * element.geometry.width - 6} y={element.geometry.y + handle.y * element.geometry.height - 6} width={12} height={12} onPointerDown={event => startResize(event, element, handle.corner)} onPointerMove={continueResize} onPointerUp={() => {if(resize)commitGeometry(resize.id);setResize(null)}} onPointerCancel={() => setResize(null)}/>) }
    </g>)}
  </svg>{contextMenu&&<div className="canvas-context-menu" style={{left:contextMenu.x,top:contextMenu.y}}><ContextMenu kind={contextMenu.kind} onAction={contextAction}/></div>}<p className="inspection" aria-live="polite">{selectedId ? `Selecionado: ${selectedId}. Arraste para mover ou use as alças nos cantos para redimensionar.` : 'Selecione uma entidade. Arraste ou use as setas para mover.'}</p><CanvasToolbar onReorganize={reorganize} grid={grid} snap={snap} guides={guides} onToggle={onTogglePreference}/></section>
}

const initialSource = (text: string) => ({ text, validText: text, validRevision: 0, status: 'valid' as const, diagnostics: [] })
const initialWorkspace: WorkspaceSnapshot = { revision: 0, name: 'Payments Flow', adl: initialSource(source), adls: initialSource(appliedStylesheet), placements: {}, conversation: [], viewport: { x: 0, y: 0, zoom: 1 }, selection: [], preferences: defaultPreferences }
const workspaceController = new WorkspaceController(initialWorkspace)
const useWorkspaceStore = createWorkspaceStore(workspaceController)
const commandId = () => globalThis.crypto?.randomUUID?.() ?? `command-${Date.now()}-${Math.random()}`

export function App() {
  const snapshot = useWorkspaceStore(state=>state.snapshot)
  const [renderedModel, setRenderedModel] = useState<DiagramModel>(model)
  const [resolvedStyles, setResolvedStyles] = useState<ResolvedDiagramStyles|undefined>()
  const [newOpen,setNewOpen]=useState(false)
  const [isMobile,setIsMobile]=useState(false)
  const [restoring,setRestoring]=useState(true)
  const [recoveryWarning,setRecoveryWarning]=useState<string|null>(null)
  const restoredRef=useRef(false)
  const repository=useMemo(()=>new WorkspaceRepository(new BrowserStorageAdapter()),[])
  useEffect(()=>{if(restoredRef.current)return;restoredRef.current=true;void repository.restore('current').then(result=>{const envelope=result.status==='restored'?result.envelope:undefined,document=envelope?.document??(result.status==='recovered'?result.document:undefined),persistedPreferences=envelope?.preferences??(result.status==='recovered'?result.preferences:undefined);if(document){const revision=envelope?.revision??Math.max(document.adl.validRevision,document.adls.validRevision);workspaceController.restore({revision,name:document.name,adl:{...document.adl,status:document.adl.text===document.adl.validText?'valid':'invalid',diagnostics:[]},adls:{...document.adls,status:document.adls.text===document.adls.validText?'valid':'invalid',diagnostics:[]},placements:envelope?.visual.placements??{},viewport:envelope?.visual.viewport??{x:0,y:0,zoom:1},selection:[],conversation:(envelope?.conversation.messages??[]).filter((item):item is {id:string;role:'user'|'assistant'|'system';content:string}=>typeof item==='object'&&item!==null&&typeof (item as {id?:unknown}).id==='string'&&typeof (item as {content?:unknown}).content==='string'&&['user','assistant','system'].includes(String((item as {role?:unknown}).role))),preferences:persistedPreferences?{theme:persistedPreferences.theme,panel:persistedPreferences.panel,canvas:persistedPreferences.canvas}:defaultPreferences})}if(result.status==='recovered'&&result.warnings.length)setRecoveryWarning(result.warnings.map(item=>item.message).join(' '));setRestoring(false)})},[repository])
  const sourceBinding = useMemo(() => createSourceBinding(setRenderedModel, 30), [])
  useEffect(()=>{const media=matchMedia('(max-width: 920px)'),update=()=>setIsMobile(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[])
  useEffect(() => () => sourceBinding.dispose(), [sourceBinding])
  const applyStyles=useCallback((nextAdl:string,nextStylesheet:string)=>{const document=parse(nextAdl),hasReference=document.ok&&document.document.stylesheetReference!==undefined;const pipelineSource=hasReference?nextAdl:`stylesheet "./applied.adls"\n${nextAdl}`;void runStylesheetPipeline({adlText:pipelineSource,adlUri:'memory:/editor.adl',loadStylesheet:async()=>({text:nextStylesheet,uri:'memory:/applied.adls'})}).then(result=>{if(result.ok)setResolvedStyles(result.styles)})},[])
  const dispatchSource=useCallback((type:'source.replace-adl'|'source.replace-adls',text:string)=>workspaceController.dispatch({id:commandId(),type,baseRevision:workspaceController.getSnapshot().revision,origin:type.endsWith('adls')?'adls':'adl',payload:{text}}),[])
  const handleSourceChange=useCallback((text:string)=>{const result=dispatchSource('source.replace-adl',text);if(result.ok&&result.changed){sourceBinding.schedule(text);applyStyles(text,workspaceController.getSnapshot().adls.validText)}},[applyStyles,dispatchSource,sourceBinding])
  const handleStylesheetChange=useCallback((text:string)=>{const result=dispatchSource('source.replace-adls',text);if(result.ok&&result.changed)applyStyles(workspaceController.getSnapshot().adl.validText,text)},[applyStyles,dispatchSource])
  const handleModelChange=useCallback((next:DiagramModel,type:'semantic.add-relation'|'semantic.update-element'|'semantic.remove-elements'|'semantic.duplicate-elements'|'semantic.update-relation'|'semantic.reverse-relation'|'semantic.remove-relation')=>{const serialized=serializeModel(next);if(!serialized.ok)return;workspaceController.dispatch({id:commandId(),type,baseRevision:workspaceController.getSnapshot().revision,origin:'canvas',payload:{source:serialized.text}})},[])
  const handleElementGeometryChange=useCallback((id:string,geometry:Box)=>{const current=workspaceController.getSnapshot(),updated=updateElementRule(current.adls.validText,{elementId:id,...geometry});if(updated.ok)handleStylesheetChange(updated.text)},[handleStylesheetChange])
  useEffect(()=>{sourceBinding.schedule(snapshot.adl.validText);applyStyles(snapshot.adl.validText,snapshot.adls.validText)},[applyStyles,snapshot.adl.validText,snapshot.adls.validText,sourceBinding])
  useEffect(()=>{const preference=snapshot.preferences?.theme??'system',dark=preference==='dark'||(preference==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light'},[snapshot.preferences?.theme])
  const assistance=useAssistance({source:snapshot.adl.validText,revision:snapshot.revision,messages:snapshot.conversation,onApply:(proposal,messages)=>workspaceController.dispatch({id:commandId(),type:'assistant.apply-proposal',baseRevision:proposal.baseRevision,origin:'assistant',payload:{source:proposal.source,summary:proposal.summary,messages}}).ok,onFailure:messages=>workspaceController.recordConversation(messages)})
  useEffect(()=>{if(restoring)return;const timer=setTimeout(()=>{const current=workspaceController.getSnapshot(),preferences=current.preferences??defaultPreferences,envelope:PersistedWorkspaceEnvelope={format:'adl-workspace-v2',revision:current.revision,document:{name:current.name,adl:{text:current.adl.text,validText:current.adl.validText,validRevision:current.adl.validRevision},adls:{text:current.adls.text,validText:current.adls.validText,validRevision:current.adls.validRevision}},visual:{version:2,documentRevision:current.revision,placements:current.placements,viewport:current.viewport??{x:0,y:0,zoom:1}},conversation:{version:1,messages:current.conversation},preferences:{version:1,...preferences},savedAt:new Date().toISOString()};void repository.save('current',envelope).then(status=>{if(status.status==='failed')setRecoveryWarning(status.message)})},500);return()=>clearTimeout(timer)},[repository,restoring,snapshot])
  const exportCurrent=useCallback(async(format:'png'|'adl'|'adls')=>{const current=workspaceController.getSnapshot();if(format==='adl'||format==='adls'){const result=await createExport({format,name:current.name,revision:current.revision,source:format==='adl'?current.adl.text:current.adls.text});if(result.ok)downloadArtifact(result.artifact);return}const layoutResult=await calculateLayout(renderedModel);if(!layoutResult.ok)return;const entities=[...renderedModel.elements,...renderedModel.groups].map(entity=>{const id=entity.identity.value,base=layoutResult.layout.nodes[id],placement=current.placements[id] as Partial<Box>|undefined;return{id,x:placement?.x??base?.x??0,y:placement?.y??base?.y??0,width:placement?.width??base?.width??160,height:placement?.height??base?.height??72,label:entity.name}}),relations=renderedModel.relations.map(relation=>({id:relation.identity.value,sourceId:relation.source.identity.value,targetId:relation.target.identity.value,label:relation.name??undefined,points:layoutResult.layout.edges[relation.identity.value]?.points??[]}));const result=await createExport({format:'png',name:current.name,revision:current.revision,scene:createExportScene(entities,24,relations)});if(result.ok)downloadArtifact(result.artifact)},[renderedModel])
  const cycleTheme=()=>{const preferences=snapshot.preferences??defaultPreferences,next=preferences.theme==='system'?'light':preferences.theme==='light'?'dark':'system';workspaceController.updatePreferences({...preferences,theme:next})}
  const togglePanel=()=>{const preferences=snapshot.preferences??defaultPreferences;workspaceController.updatePreferences({...preferences,panel:{...preferences.panel,collapsed:!preferences.panel.collapsed}})}
  const toggleCanvasPreference=(key:'grid'|'snap'|'guides')=>{const preferences=snapshot.preferences??defaultPreferences,field=key==='grid'?'gridVisible':key==='snap'?'snapEnabled':'guidesEnabled';workspaceController.updatePreferences({...preferences,canvas:{...preferences.canvas,[field]:!preferences.canvas[field]}})}
  const resizePanel=(event:ReactPointerEvent<HTMLDivElement>)=>{const preferences=workspaceController.getSnapshot().preferences??defaultPreferences,start=event.clientX,width=preferences.panel.expandedWidth;const move=(next:PointerEvent)=>workspaceController.updatePreferences({...preferences,panel:{...preferences.panel,expandedWidth:Math.min(520,Math.max(280,width+next.clientX-start))}}),up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up)};addEventListener('pointermove',move);addEventListener('pointerup',up)}
  const selectionKind=useMemo<"element"|"relation"|undefined>(()=>{const last=snapshot.selection?.at(-1);if(!last)return undefined;if(renderedModel.relations.some(item=>item.identity.value===last))return "relation";if(renderedModel.elements.some(item=>item.identity.value===last))return "element";return undefined},[renderedModel,snapshot.selection])
  const duplicateSelection=useCallback(()=>{const selection=workspaceController.getSnapshot().selection??[];if(!selection.length)return;const taken=new Set([...renderedModel.elements,...renderedModel.relations,...renderedModel.groups].map(item=>item.identity.value));const nextIds:string[]=[];const elements=renderedModel.elements.flatMap(item=>{if(!selection.includes(item.identity.value))return [item];let index=2,id=`${item.identity.value}-${index}`;while(taken.has(id))id=`${item.identity.value}-${++index}`;taken.add(id);nextIds.push(id);return [item,{...item,identity:{...item.identity,value:id},name:`${item.name} copy`}]});const relations=renderedModel.relations.flatMap(item=>{if(!selection.includes(item.identity.value))return [item];let index=2,id=`${item.identity.value}-${index}`;while(taken.has(id))id=`${item.identity.value}-${++index}`;taken.add(id);nextIds.push(id);return [item,{...item,identity:{...item.identity,value:id},name:item.name?`${item.name} copy`:null}]});if(nextIds.length){handleModelChange({...renderedModel,elements,relations},'semantic.duplicate-elements');workspaceController.updateEphemeral({selection:nextIds})}},[handleModelChange,renderedModel])
  const deleteSelection=useCallback(()=>{const selection=workspaceController.getSnapshot().selection??[];if(!selection.length)return;const ids=new Set(selection),elements=renderedModel.elements.filter(item=>!ids.has(item.identity.value)),elementIds=new Set(elements.map(item=>item.identity.value)),relations=renderedModel.relations.filter(item=>!ids.has(item.identity.value)&&elementIds.has(item.source.identity.value)&&elementIds.has(item.target.identity.value)),groups=renderedModel.groups.filter(item=>!ids.has(item.identity.value)).map(group=>({...group,members:group.members.filter(member=>elementIds.has(member.identity.value))}));handleModelChange({...renderedModel,elements,relations,groups},selection.some(id=>renderedModel.relations.some(item=>item.identity.value===id))?'semantic.remove-relation':'semantic.remove-elements');workspaceController.updateEphemeral({selection:[]})},[handleModelChange,renderedModel])
  const reverseSelection=useCallback(()=>{const id=workspaceController.getSnapshot().selection?.at(-1),relation=renderedModel.relations.find(item=>item.identity.value===id);if(!relation)return;handleModelChange({...renderedModel,relations:renderedModel.relations.map(item=>item===relation?{...item,source:item.target,target:item.source}:item)},'semantic.reverse-relation')},[handleModelChange,renderedModel])
  const reset=()=>{setNewOpen(false);workspaceController.reset()}
  const preferences=snapshot.preferences??defaultPreferences
  if(restoring)return <main className="app-shell"><p role="status">Restaurando workspace…</p></main>
  const editor=<div className="editor-shell">{recoveryWarning&&<div className="recovery-warning" role="status">{recoveryWarning}</div>}<EditorTabs adlText={snapshot.adl.text} stylesheetText={snapshot.adls.text} onAdlChange={handleSourceChange} onStylesheetChange={handleStylesheetChange} assistant={<AssistantConversation messages={assistance.messages} busy={assistance.flow.status==='generating'||assistance.flow.status==='applying'} error={assistance.flow.status==='failed'?assistance.flow.message:undefined} onSubmit={intent=>void assistance.submit(intent)} onRetry={assistance.retry}/>} /></div>
  const preview=resolvedStyles?<DiagramPreview model={renderedModel} styles={resolvedStyles} selectedIds={snapshot.selection??[]} viewport={snapshot.viewport} onViewportChange={viewport=>workspaceController.updateEphemeral({viewport})} onSelectionChange={selection=>workspaceController.updateEphemeral({selection})} onModelChange={handleModelChange} onElementGeometryChange={handleElementGeometryChange} grid={preferences.canvas.gridVisible} snap={preferences.canvas.snapEnabled} guides={preferences.canvas.guidesEnabled} gridSize={preferences.canvas.gridSize} onTogglePreference={toggleCanvasPreference}/>:<section className="preview" aria-label="Diagrama Payments Flow"><h2 className="sr-only">Diagrama</h2><p>Aplicando stylesheet…</p></section>
  return <main className="app-shell"><TopBar name={snapshot.name} onNameChange={name=>workspaceController.dispatch({id:commandId(),type:'workspace.rename',baseRevision:workspaceController.getSnapshot().revision,origin:'workspace',payload:{name}})} onNew={()=>setNewOpen(true)} onUndo={()=>workspaceController.undo()} onRedo={()=>workspaceController.redo()} onExport={format=>void exportCurrent(format)} onTheme={cycleTheme} theme={preferences.theme} panelCollapsed={preferences.panel.collapsed} onPanelToggle={togglePanel} selectionKind={selectionKind} onDuplicate={duplicateSelection} onDelete={deleteSelection} onReverse={reverseSelection}/>{isMobile?<><div className="workspace-grid mobile-workspace">{preview}</div><MobileDrawer open={!preferences.panel.collapsed} onClose={togglePanel}>{editor}</MobileDrawer></>:<div className="workspace-grid" style={{gridTemplateColumns:preferences.panel.collapsed?'0 minmax(0,1fr)':`${preferences.panel.expandedWidth}px 4px minmax(0,1fr)`}}>{editor}{!preferences.panel.collapsed&&<div className="panel-resizer" role="separator" aria-label="Redimensionar painel" aria-orientation="vertical" aria-valuemin={280} aria-valuemax={520} aria-valuenow={preferences.panel.expandedWidth} tabIndex={0} onPointerDown={resizePanel} onKeyDown={event=>{if(event.key==='ArrowLeft'||event.key==='ArrowRight')workspaceController.updatePreferences({...preferences,panel:{...preferences.panel,expandedWidth:Math.min(520,Math.max(280,preferences.panel.expandedWidth+(event.key==='ArrowLeft'?-16:16)))}})}}/>}{preview}</div>}<NewDiagramDialog open={newOpen} onCancel={()=>setNewOpen(false)} onConfirm={reset}/></main>
}
