import { useEffect, useState } from "react";
import { createVisualHistory, dispatchVisualCommand, MDL_CONNECTOR_TYPES, redoVisualCommand, undoVisualCommand, type MdlConnectorType, type VisualCommand, type VisualError, type VisualHistory, type VisualModel } from "./commands.js";

const ELEMENT_TYPES = ["service", "database", "queue", "client", "external", "component"] as const;
const CONNECTOR_LABELS:Record<MdlConnectorType,string>={link:"Link", "always-link":"Always link", specialization:"Especialização", "virtual-link":"Virtual link", composition:"Composição"};

export function VisualEditor({ initialModel, onModelChange }: { readonly initialModel?: VisualModel; readonly onModelChange?: (model: VisualModel) => void }) {
  const [history, setHistory] = useState<VisualHistory>(() => createVisualHistory(initialModel));
  const [error, setError] = useState<VisualError | null>(null);
  const [pendingDelete, setPendingDelete] = useState<string | null>(null);
  useEffect(() => onModelChange?.(history.present), [history.present, onModelChange]);
  const run = (command: VisualCommand): boolean => { const result = dispatchVisualCommand(history, command); if (result.ok) { setHistory(result.history); setError(null); setPendingDelete(null); return true; } setError(result.error); if (result.error.code === "DEPENDENT_RELATIONS" && command.type === "remove-entity") setPendingDelete(command.id); return false; };
  const model = history.present;
  return <section className="visual-editor" aria-labelledby="visual-editor-title"><div className="panel-heading"><h2 id="visual-editor-title">Editor visual</h2><div className="toolbar"><button type="button" onClick={() => setHistory(undoVisualCommand(history))} disabled={!history.past.length}>Desfazer</button><button type="button" onClick={() => setHistory(redoVisualCommand(history))} disabled={!history.future.length}>Refazer</button></div></div>
    <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); if (run({ type: "create-element", id: String(data.get("id")), name: String(data.get("name")), elementType: String(data.get("elementType")) })) event.currentTarget.reset(); }}><h3>Novo elemento</h3><label>ID <input name="id" required pattern="[A-Za-z_][A-Za-z0-9_-]*" /></label><label>Nome <input name="name" required /></label><label>Tipo <select name="elementType" required defaultValue="service">{ELEMENT_TYPES.map(type => <option key={type} value={type}>{type}</option>)}</select></label><button type="submit">Adicionar elemento</button></form>
    <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); run({ type: "create-relation", id: String(data.get("id")), sourceId: String(data.get("source")), targetId: String(data.get("target")), name: String(data.get("name")), relationType: String(data.get("relationType")) as MdlConnectorType }); }}><h3>Nova relação</h3><label>ID <input name="id" required /></label><label>Origem <select name="source" required>{Object.keys(model.elements).map(id => <option key={id}>{id}</option>)}</select></label><label>Destino <select name="target" required>{Object.keys(model.elements).map(id => <option key={id}>{id}</option>)}</select></label><label>Conector <select name="relationType" defaultValue="link">{MDL_CONNECTOR_TYPES.map(type=><option key={type} value={type}>{CONNECTOR_LABELS[type]}</option>)}</select></label><label>Nome <input name="name" /></label><button type="submit" disabled={Object.keys(model.elements).length < 2}>Adicionar relação</button></form>
    <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); run({ type: "create-group", id: String(data.get("id")), name: String(data.get("name")), memberIds: data.getAll("members").map(String) }); }}><h3>Novo grupo</h3><label>ID <input name="id" required /></label><label>Nome <input name="name" required /></label><fieldset><legend>Membros</legend>{Object.keys(model.elements).map(id => <label key={id}><input type="checkbox" name="members" value={id}/>{id}</label>)}</fieldset><button type="submit" disabled={!Object.keys(model.elements).length}>Adicionar grupo</button></form>
    {model.selection.length === 1 && model.elements[model.selection[0]] && <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); run({ type: "update-element", id: model.selection[0], name: String(data.get("name")), elementType: String(data.get("elementType")) }); }}><h3>Editar {model.selection[0]}</h3><label>Nome <input name="name" defaultValue={model.elements[model.selection[0]].name} required /></label><label>Tipo <input name="elementType" defaultValue={model.elements[model.selection[0]].type} required /></label><button type="submit">Salvar elemento</button></form>}
    {error && <p className="error" role="alert">{error.message}</p>}{pendingDelete && <button className="danger" type="button" onClick={() => run({ type: "remove-entity", id: pendingDelete, cascade: true })}>Confirmar remoção de {pendingDelete} e dependências</button>}
    <div className="entity-list" aria-label="Entidades visuais">{Object.values(model.elements).map(element => <article key={element.id} data-selected={model.selection.includes(element.id)}><button type="button" className="entity" onClick={() => run({ type: "select", ids: [element.id] })}><strong>{element.name}</strong><span>{element.id} · {element.type}</span></button><button type="button" aria-label={`Remover ${element.name}`} onClick={() => run({ type: "remove-entity", id: element.id, cascade: false })}>Remover</button></article>)}{Object.values(model.relations).map(relation => <article key={relation.id}><span>{relation.name || relation.id}: {relation.sourceId} → {relation.targetId}</span><button type="button" aria-label={`Remover relação ${relation.id}`} onClick={() => run({ type: "remove-entity", id: relation.id, cascade: false })}>Remover</button></article>)}{Object.values(model.groups).map(group => <article key={group.id}><span>{group.name}: {group.memberIds.join(', ')}</span><button type="button" aria-label={`Remover grupo ${group.id}`} onClick={() => run({ type: "remove-entity", id: group.id, cascade: false })}>Remover</button></article>)}</div>
  </section>;
}
