export interface LocalDocument { readonly id: string; readonly source: string; readonly updatedAt: string }
export interface VisualStateEnvelope { readonly version: 1; readonly documentRevision: number; readonly value: unknown }
export interface PersistedRevision { readonly revision: number; readonly document: LocalDocument; readonly visual?: VisualStateEnvelope }
export type SaveStatus = { readonly status: "idle" | "pending" | "saved"; readonly revision?: number } | { readonly status: "failed"; readonly message: string };
export interface PersistenceRecord { readonly format: "adl-local-v1"; readonly confirmed: PersistedRevision }
export interface StorageAdapter { get(key: string): string | null | Promise<string | null>; set(key: string, value: string): void | Promise<void>; remove?(key: string): void | Promise<void> }
export interface PersistedSource { readonly text: string; readonly validText: string; readonly validRevision: number }
export interface PersistedWorkspaceEnvelope { readonly format: "adl-workspace-v2"; readonly revision: number; readonly document: { readonly name: string; readonly adl: PersistedSource; readonly adls: PersistedSource }; readonly visual: { readonly version: 2; readonly documentRevision: number; readonly placements: Readonly<Record<string, unknown>>; readonly viewport: { readonly x: number; readonly y: number; readonly zoom: number } }; readonly conversation: { readonly version: 1; readonly messages: readonly unknown[] }; readonly preferences: { readonly version: 1; readonly theme: "system" | "light" | "dark"; readonly panel: { readonly collapsed: boolean; readonly expandedWidth: number; readonly mode: "assistant" | "adl" | "adls" }; readonly canvas: { readonly gridVisible: boolean; readonly snapEnabled: boolean; readonly guidesEnabled: boolean; readonly gridSize: number } }; readonly savedAt: string }
export type RestoreWarningCode = "CORRUPTED_RECORD" | "UNSUPPORTED_FORMAT" | "INCOMPATIBLE_VISUAL_STATE" | "INCOMPATIBLE_CONVERSATION" | "INCOMPATIBLE_PREFERENCES" | "STORAGE_UNAVAILABLE";
export interface RestoreWarning { readonly code: RestoreWarningCode; readonly message: string }
export type WorkspaceRestoreResult = { readonly status: "empty" } | { readonly status: "restored"; readonly envelope: PersistedWorkspaceEnvelope; readonly warnings: readonly RestoreWarning[] } | { readonly status: "recovered"; readonly document?: PersistedWorkspaceEnvelope["document"]; readonly preferences?: PersistedWorkspaceEnvelope["preferences"]; readonly warnings: readonly RestoreWarning[] };
