import type { PersistedRevision, PersistedWorkspaceEnvelope, PersistenceRecord, SaveStatus, StorageAdapter, WorkspaceRestoreResult } from "./model.js";
export interface RestoreResult { readonly revision?: PersistedRevision; readonly warning?: string }
const validRecord = (value: unknown): value is PersistenceRecord => { if (!value || typeof value !== "object") return false; const candidate = value as Partial<PersistenceRecord>; return candidate.format === "adl-local-v1" && typeof candidate.confirmed?.document?.source === "string" && typeof candidate.confirmed.revision === "number"; };
export class LocalDocumentRepository {
  readonly #storage: StorageAdapter; readonly #prefix: string; #status: SaveStatus = { status: "idle" };
  constructor(storage: StorageAdapter, prefix = "adl:document:") { this.#storage = storage; this.#prefix = prefix; }
  get status(): SaveStatus { return this.#status; }
  async save(id: string, revision: PersistedRevision): Promise<SaveStatus> { this.#status = { status: "pending", revision: revision.revision }; const key = this.#prefix + id; try { await this.#storage.set(key, JSON.stringify({ format: "adl-local-v1", confirmed: revision } satisfies PersistenceRecord)); this.#status = { status: "saved", revision: revision.revision }; } catch (cause) { this.#status = { status: "failed", message: cause instanceof Error ? cause.message : "Local storage failed." }; } return this.#status; }
  async restore(id: string): Promise<RestoreResult> { const raw = await this.#storage.get(this.#prefix + id); if (raw === null) return {}; try { const parsed: unknown = JSON.parse(raw); if (!validRecord(parsed)) return { warning: "Stored document is not compatible." }; const visual = parsed.confirmed.visual; if (visual && (visual.version !== 1 || visual.documentRevision !== parsed.confirmed.revision)) return { revision: { ...parsed.confirmed, visual: undefined }, warning: "Incompatible visual state was discarded." }; return { revision: parsed.confirmed }; } catch { return { warning: "Stored document is corrupted." }; } }
}
export class MemoryStorage implements StorageAdapter { readonly #values = new Map<string, string>(); get(key: string): string | null { return this.#values.get(key) ?? null; } set(key: string, value: string): void { this.#values.set(key, value); } remove(key: string): void { this.#values.delete(key); } }

const validWorkspace = (value: unknown): value is PersistedWorkspaceEnvelope => { if (!value || typeof value !== "object") return false; const item = value as Partial<PersistedWorkspaceEnvelope>; return item.format === "adl-workspace-v2" && Number.isInteger(item.revision) && typeof item.document?.adl?.text === "string" && typeof item.document?.adls?.text === "string" && item.visual?.version === 2 && item.conversation?.version === 1 && item.preferences?.version === 1; };
export class WorkspaceRepository {
  readonly #storage: StorageAdapter; readonly #prefix: string;
  constructor(storage: StorageAdapter, prefix = "adl:workspace:") { this.#storage = storage; this.#prefix = prefix; }
  async save(id: "current", envelope: PersistedWorkspaceEnvelope): Promise<SaveStatus> { try { await this.#storage.set(this.#prefix + id, JSON.stringify(envelope)); return { status: "saved", revision: envelope.revision }; } catch (cause) { return { status: "failed", message: cause instanceof Error ? cause.message : "Local storage failed." }; } }
  async restore(id: "current"): Promise<WorkspaceRestoreResult> { let raw: string | null; try { raw = await this.#storage.get(this.#prefix + id); } catch { return { status: "recovered", warnings: [{ code: "STORAGE_UNAVAILABLE", message: "Local storage is unavailable." }] }; } if (raw === null) return { status: "empty" }; try { const parsed: unknown = JSON.parse(raw); if (validRecord(parsed)) { const revision=parsed.confirmed.revision,source=parsed.confirmed.document.source;return{status:"recovered",document:{name:parsed.confirmed.document.id,adl:{text:source,validText:source,validRevision:revision},adls:{text:'stylesheet version "1.0" {}',validText:'stylesheet version "1.0" {}',validRevision:revision}},preferences:{version:1,theme:"system",panel:{collapsed:false,expandedWidth:356,mode:"assistant"},canvas:{gridVisible:true,snapEnabled:true,guidesEnabled:true,gridSize:24}},warnings:[{code:"UNSUPPORTED_FORMAT",message:"Legacy workspace migrated to version 2."}]}; } if (!validWorkspace(parsed)) return { status: "recovered", warnings: [{ code: "UNSUPPORTED_FORMAT", message: "Stored workspace is incompatible." }] }; if (parsed.visual.documentRevision !== parsed.revision) return { status: "recovered", document: parsed.document, preferences: parsed.preferences, warnings: [{ code: "INCOMPATIBLE_VISUAL_STATE", message: "Incompatible visual state was discarded." }] }; return { status: "restored", envelope: parsed, warnings: [] }; } catch { return { status: "recovered", warnings: [{ code: "CORRUPTED_RECORD", message: "Stored workspace is corrupted." }] }; } }
  async clear(id: "current"): Promise<void> { await this.#storage.remove?.(this.#prefix + id); }
}
