import { expect, test } from '@playwright/test'

test('edits ADL with current diagnostics and keyboard controls', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Editor ADL' })).toBeVisible()
  await expect(page.getByText('Documento válido.')).toBeVisible()
  await page.locator('.cm-content').click()
  await page.keyboard.press('Control+End')
  await page.keyboard.type(' invalid')
  await expect(page.getByRole('heading', { name: /Diagnósticos \([1-9]/ })).toBeVisible()
  await page.getByRole('button', { name: 'Desfazer' }).first().click()
})

test('creates, relates, selects and safely removes visual entities by keyboard', async ({ page }) => {
  await page.goto('/')
  const visual = page.getByRole('heading', { name: 'Editor visual' }).locator('..').locator('..')
  await expect(visual.getByLabel('Tipo').first()).toHaveRole('combobox')
  await visual.getByLabel('ID').first().fill('worker'); await visual.getByLabel('Nome').first().fill('Worker'); await visual.getByLabel('Tipo').first().selectOption('service'); await visual.getByRole('button', { name: 'Adicionar elemento' }).click()
  await expect(page.getByRole('img', { name: /Worker/ }).getByText('Worker', { exact: true })).toBeVisible()
  const relation = visual.getByRole('heading', { name: 'Nova relação' }).locator('..'); await relation.locator('input[name="id"]').fill('dispatches'); await relation.locator('select[name="source"]').selectOption('api'); await relation.locator('select[name="target"]').selectOption('worker'); await relation.getByRole('button', { name: 'Adicionar relação' }).click()
  await visual.getByRole('button', { name: /Worker.*worker/ }).focus(); await page.keyboard.press('Enter')
  await visual.getByRole('button', { name: 'Remover Worker' }).click(); await expect(visual.getByRole('alert')).toContainText('dependentes'); await visual.getByRole('button', { name: /Confirmar remoção/ }).click(); await expect(visual.getByText('Worker', { exact: true })).toHaveCount(0)
})

test('moves diagram elements with pointer and keyboard without changing ADL', async ({ page }) => {
  await page.goto('/')
  const sourceBefore = await page.locator('.cm-content').textContent()
  const api = page.getByRole('img').getByRole('button', { name: /API/ })
  const initial = await api.boundingBox()
  if (!initial) throw new Error('API element is not visible')
  await api.hover()
  await page.mouse.down()
  await page.mouse.move(initial.x + initial.width / 2 + 80, initial.y + initial.height / 2 + 40)
  await page.mouse.up()
  const dragged = await api.boundingBox()
  expect(dragged?.x).toBeGreaterThan(initial.x + 50)
  await api.focus()
  await page.keyboard.press('ArrowRight')
  const keyboardMoved = await api.boundingBox()
  expect(keyboardMoved?.x).toBeGreaterThan(dragged?.x ?? 0)
  await expect(page.locator('.cm-content')).toHaveText(sourceBefore ?? '')
})

test('debounces valid code into the canvas and keeps the last valid render on errors', async ({ page }) => {
  await page.goto('/')
  const editor = page.locator('.cm-content')
  const diagram = page.getByRole('img')
  const beforeInvalid = await diagram.innerHTML()
  await editor.click()
  await page.keyboard.press('Control+A')
  await page.keyboard.insertText('invalid source')
  await page.waitForTimeout(60)
  expect(await diagram.innerHTML()).toBe(beforeInvalid)
  await page.keyboard.press('Control+A')
  await page.keyboard.insertText('adl version "1.0" diagram { element worker { name "Worker" type "service" } }')
  await expect(diagram.getByText('Worker', { exact: true })).toBeVisible()
  await expect(diagram.getByText('API', { exact: true })).toHaveCount(0)
})
