import type { Paint, StyleDiagnostic, StyleRule, StylesheetDocument, ValidatedRule, ValidatedStylesheet } from "./syntax.js";

const common=new Set(["text-paint","font-size","font-family","font-weight","font-style","text-decoration","text-align","vertical-align"]);
const element=new Set([...common,"shape","width","height","fill","border-paint","border-width","border-radius","orientation","rotation","x","y"]);
const relation=new Set([...common,"line-paint","line-width"]);
const hex=/^#[0-9A-F]{6}(?:[0-9A-F]{2})?$/i;
const number=(value:string,unit:string):number|undefined=>{const match=new RegExp(`^([+-]?(?:\\d+(?:\\.\\d+)?|\\.\\d+))${unit}$`).exec(value);if(!match)return undefined;const parsed=Number(match[1]);return Number.isFinite(parsed)?parsed:undefined};
const angle=(value:string):number|undefined=>{const parsed=number(value,"deg");return parsed===undefined?undefined:((parsed%360)+360)%360};
export function parsePaint(value:string):Paint|undefined{if(hex.test(value))return{kind:"solid",color:value.toUpperCase()};const match=/^linear-gradient\(\s*([^,]+)\s*,\s*(.+)\)$/i.exec(value);if(!match)return undefined;const a=angle(match[1]!.trim());if(a===undefined)return undefined;const stops=match[2]!.split(",").map(part=>/^\s*(#[0-9a-f]{6}(?:[0-9a-f]{2})?)\s+([+-]?(?:\d+(?:\.\d+)?|\.\d+))%\s*$/i.exec(part));if(stops.length<2||stops.some(stop=>!stop))return undefined;const normalized=stops.map(stop=>({color:stop![1]!.toUpperCase(),offset:Number(stop![2])/100}));if(normalized.some(stop=>!Number.isFinite(stop.offset)||stop.offset<0||stop.offset>1)||normalized.some((stop,index)=>index>0&&stop.offset<normalized[index-1]!.offset))return undefined;return{kind:"linear-gradient",angle:a,stops:normalized}}
function value(property:string,raw:string):unknown|undefined{if(["fill","border-paint","line-paint","text-paint"].includes(property))return parsePaint(raw);if(["width","height"].includes(property)){const parsed=number(raw,"px");return parsed!==undefined&&parsed>=24&&parsed<=4096?parsed:undefined}if(["border-width","line-width"].includes(property)){const parsed=number(raw,"px");return parsed!==undefined&&parsed>=0&&parsed<=32?parsed:undefined}if(property==="border-radius"){const parsed=number(raw,"px");return parsed!==undefined&&parsed>=0&&parsed<=2048?parsed:undefined}if(property==="font-size"){const parsed=number(raw,"px");return parsed!==undefined&&parsed>=8&&parsed<=256?parsed:undefined}if(property==="x"||property==="y")return number(raw,"px");if(property==="rotation")return angle(raw);if(property==="shape"&&["rectangle","ellipse","cylinder","user","parallelogram"].includes(raw))return raw;if(property==="orientation"&&["horizontal","vertical"].includes(raw))return raw;if(property==="text-align"&&["left","center","right"].includes(raw))return raw;if(property==="vertical-align"&&["top","middle","bottom"].includes(raw))return raw;if(property==="font-weight"&&["normal","bold"].includes(raw))return raw;if(property==="font-style"&&["normal","italic"].includes(raw))return raw;if(property==="text-decoration"&&["none","underline"].includes(raw))return raw;if(property==="font-family"){const families=raw.split(",").map(item=>item.trim()).filter(Boolean);return families.length>0&&["serif","sans-serif","monospace"].includes(families.at(-1)!)?families:undefined}return undefined}
function diagnostic(rule:StyleRule,code:StyleDiagnostic["code"],message:string,range=rule.range):StyleDiagnostic{return{code,severity:"error",message,uri:"",range}}
export function validateStylesheet(document:StylesheetDocument):ValidatedStylesheet{const diagnostics:StyleDiagnostic[]=[];const rules:ValidatedRule[]=document.rules.map(rule=>{const allowed=rule.selector.target==="global"?common:rule.selector.target==="element"?element:relation;const values:Record<string,unknown>={};for(const declaration of rule.declarations){if(!common.has(declaration.property)&&!element.has(declaration.property)&&!relation.has(declaration.property)){diagnostics.push({...diagnostic(rule,"STYLE_UNKNOWN_PROPERTY",`Unknown style property ${JSON.stringify(declaration.property)}.`,declaration.range),uri:document.uri});continue}if(!allowed.has(declaration.property)){diagnostics.push({...diagnostic(rule,"STYLE_PROPERTY_SCOPE",`Property ${declaration.property} is not valid for this selector.`,declaration.range),uri:document.uri});continue}if((declaration.property==="x"||declaration.property==="y")&&(rule.selector.target!=="element"||rule.selector.kind!=="id")){diagnostics.push({...diagnostic(rule,"STYLE_PROPERTY_SCOPE",`${declaration.property} is only valid for an element id selector.`,declaration.range),uri:document.uri});continue}const parsed=value(declaration.property,declaration.value);if(parsed===undefined){diagnostics.push({...diagnostic(rule,"STYLE_INVALID_VALUE",`Invalid value ${JSON.stringify(declaration.value)} for ${declaration.property}.`,declaration.range),uri:document.uri});continue}if(Object.hasOwn(values,declaration.property))diagnostics.push({code:"STYLE_OVERRIDE",severity:"warning",message:`Later declaration overrides ${declaration.property}.`,uri:document.uri,range:declaration.range});values[declaration.property]=parsed}if(Object.hasOwn(values,"x")!==Object.hasOwn(values,"y"))diagnostics.push({...diagnostic(rule,"STYLE_INVALID_VALUE","Properties x and y must be declared together."),uri:document.uri});if(values["border-radius"]!==undefined&&values.shape!==undefined&&values.shape!=="rectangle")diagnostics.push({...diagnostic(rule,"STYLE_INVALID_VALUE","border-radius is only compatible with shape rectangle."),uri:document.uri});return{source:rule,values}});return{source:document,rules,diagnostics,valid:!diagnostics.some(item=>item.severity==="error")}}
