import { commitTransaction, createHistory, redo, undo, validateCommandRevision, type CommandHistory, type CommandResult, type WorkspaceCommand, type WorkspaceTransaction } from "@adl/workspace";
import { parse } from "@adl/parser";
import { defaultPreferences, type WorkspacePreferences } from "./workspace-preferences.js";

export interface SourceState { readonly text: string; readonly validText: string; readonly validRevision: number; readonly status: "valid" | "invalid"; readonly diagnostics: readonly string[] }
export interface ConversationMessage { readonly id: string; readonly role: "user" | "assistant" | "system"; readonly content: string }
export interface WorkspaceSnapshot { readonly revision: number; readonly name: string; readonly adl: SourceState; readonly adls: SourceState; readonly placements: Readonly<Record<string, unknown>>; readonly conversation: readonly ConversationMessage[]; readonly viewport?: { readonly x: number; readonly y: number; readonly zoom: number }; readonly selection?: readonly string[]; readonly preferences?: WorkspacePreferences }
type Listener = (snapshot: WorkspaceSnapshot) => void;

export class WorkspaceController {
  #snapshot: WorkspaceSnapshot; #history: CommandHistory<WorkspaceSnapshot> = createHistory(); readonly #listeners = new Set<Listener>(); #gesture: { before: WorkspaceSnapshot; preview: WorkspaceSnapshot } | undefined;
  constructor(snapshot: WorkspaceSnapshot) { this.#snapshot = { ...snapshot, viewport: snapshot.viewport ?? { x: 0, y: 0, zoom: 1 }, selection: snapshot.selection ?? [], preferences: snapshot.preferences ?? defaultPreferences }; }
  getSnapshot(): WorkspaceSnapshot { return this.#snapshot; }
  subscribe(listener: Listener): () => void { this.#listeners.add(listener); return () => this.#listeners.delete(listener); }
  #publish(): void { for (const listener of this.#listeners) listener(this.#snapshot); }
  dispatch(command: WorkspaceCommand): CommandResult { const stale = validateCommandRevision(command, this.#snapshot.revision); if (stale) return stale; const before = this.#snapshot; let after = before;
    if (command.type === "workspace.rename") { const name = (command.payload as { name: string }).name; if (name !== before.name) after = { ...before, name, revision: before.revision + 1 }; }
    else if (command.type === "source.replace-adl" || command.type === "source.replace-adls") { const key = command.type.endsWith("adl") ? "adl" : "adls"; const text = (command.payload as { text: string }).text; const valid=key==="adl"?parse(text).ok:/^\s*stylesheet\b/.test(text);if(!valid){this.#snapshot={...before,[key]:{...before[key],text,status:"invalid",diagnostics:[`${key.toUpperCase()} inválido`]}};this.#publish();return{ok:false,code:key==="adl"?"INVALID_ADL":"INVALID_ADLS",message:`${key.toUpperCase()} inválido`,currentRevision:before.revision};}if (text !== before[key].text) after = { ...before, revision: before.revision + 1, [key]: { text, validText: text, validRevision: before.revision + 1, status: "valid", diagnostics: [] } }; }
    else if(command.type==="assistant.apply-proposal"){const proposal=command.payload as{source:string;summary:string;messages?:readonly ConversationMessage[]};if(!parse(proposal.source).ok)return{ok:false,code:"INVALID_ADL",message:"Proposta ADL inválida",currentRevision:before.revision};after={...before,revision:before.revision+1,adl:{text:proposal.source,validText:proposal.source,validRevision:before.revision+1,status:"valid",diagnostics:[]},conversation:proposal.messages??[...before.conversation,{id:`${command.id}-summary`,role:"assistant",content:proposal.summary}]};}
    else if(command.type==="visual.move-elements"||command.type==="visual.resize-entity"){const placements=(command.payload as{placements?:Readonly<Record<string,unknown>>;id?:string;box?:unknown});after={...before,revision:before.revision+1,placements:placements.placements??(placements.id?{...before.placements,[placements.id]:placements.box}:before.placements)};}
    else if(command.type.startsWith("semantic.")){const source=(command.payload as{source?:string}).source;if(!source||!parse(source).ok)return{ok:false,code:"UNREPRESENTABLE_CHANGE",message:"A mudança semântica não pôde ser serializada.",currentRevision:before.revision};after={...before,revision:before.revision+1,adl:{text:source,validText:source,validRevision:before.revision+1,status:"valid",diagnostics:[]}};}
    else if (command.type === "workspace.reset") after = { ...before, revision: before.revision + 1, name: "Untitled diagram", adl: { text: "", validText: "", validRevision: before.revision + 1, status: "valid", diagnostics: [] }, adls: { text: "", validText: "", validRevision: before.revision + 1, status: "valid", diagnostics: [] }, placements: {}, conversation: [] };
    if (after === before) return { ok: true, revision: before.revision, changed: false };
    const transaction: WorkspaceTransaction<WorkspaceSnapshot> = { id: command.id, origin: command.origin, description: command.type, before, after, createdAt: Date.now() }; this.#history = commitTransaction(this.#history, transaction); this.#snapshot = after; this.#publish(); return { ok: true, revision: after.revision, changed: true, transactionId: transaction.id }; }
  undo(): CommandResult { const result = undo(this.#history); if (!result) return { ok: true, revision: this.#snapshot.revision, changed: false }; this.#history = result.history; this.#snapshot = result.snapshot; this.#publish(); return { ok: true, revision: this.#snapshot.revision, changed: true }; }
  redo(): CommandResult { const result = redo(this.#history); if (!result) return { ok: true, revision: this.#snapshot.revision, changed: false }; this.#history = result.history; this.#snapshot = result.snapshot; this.#publish(); return { ok: true, revision: this.#snapshot.revision, changed: true }; }
  beginGesture(): void { this.#gesture={before:this.#snapshot,preview:this.#snapshot}; }
  previewGesture(placements:Readonly<Record<string,unknown>>):void{if(!this.#gesture)return;this.#gesture={...this.#gesture,preview:{...this.#gesture.preview,placements}};this.#snapshot=this.#gesture.preview;this.#publish();}
  commitGesture():CommandResult{if(!this.#gesture)return{ok:true,revision:this.#snapshot.revision,changed:false};const{before,preview}=this.#gesture;this.#gesture=undefined;if(before.placements===preview.placements)return{ok:true,revision:before.revision,changed:false};const after={...preview,revision:before.revision+1};this.#history=commitTransaction(this.#history,{id:`gesture-${after.revision}`,origin:"canvas",description:"Mover elementos",before,after,createdAt:Date.now()});this.#snapshot=after;this.#publish();return{ok:true,revision:after.revision,changed:true};}
  cancelGesture():void{if(!this.#gesture)return;this.#snapshot=this.#gesture.before;this.#gesture=undefined;this.#publish();}
  updateEphemeral(patch: Partial<Pick<WorkspaceSnapshot, "selection" | "viewport">>): void { this.#snapshot = { ...this.#snapshot, ...patch }; this.#publish(); }
  updatePreferences(preferences: WorkspacePreferences): void { if (preferences === this.#snapshot.preferences) return; const before=this.#snapshot,after={...before,revision:before.revision+1,preferences};this.#history=commitTransaction(this.#history,{id:`preferences-${after.revision}`,origin:"workspace",description:"Atualizar preferências",before,after,createdAt:Date.now()});this.#snapshot=after;this.#publish(); }
  recordConversation(conversation: readonly ConversationMessage[]): void { const before=this.#snapshot,after={...before,revision:before.revision+1,conversation};this.#history=commitTransaction(this.#history,{id:`conversation-${after.revision}`,origin:"assistant",description:"Atualizar conversa",before,after,createdAt:Date.now()});this.#snapshot=after;this.#publish(); }
  restore(snapshot: WorkspaceSnapshot): void { this.#snapshot={...snapshot,viewport:snapshot.viewport??{x:0,y:0,zoom:1},selection:[],preferences:snapshot.preferences??defaultPreferences};this.#history=createHistory();this.#gesture=undefined;this.#publish(); }
  reset(): void { const before=this.#snapshot;this.#snapshot={...before,revision:before.revision+1,name:"Untitled diagram",adl:{text:'adl version "1.0" diagram {}',validText:'adl version "1.0" diagram {}',validRevision:before.revision+1,status:"valid",diagnostics:[]},adls:{text:'stylesheet version "1.0" {}',validText:'stylesheet version "1.0" {}',validRevision:before.revision+1,status:"valid",diagnostics:[]},placements:{},conversation:[],selection:[],viewport:{x:0,y:0,zoom:1}};this.#history=createHistory();this.#gesture=undefined;this.#publish(); }
  get history(): { canUndo: boolean; canRedo: boolean } { return { canUndo: this.#history.past.length > 0, canRedo: this.#history.future.length > 0 }; }
}
