import type { Box, MoveOperation, PlacementState, Point } from "./placement.js";
const finite = (p: Point) => Number.isFinite(p.x) && Number.isFinite(p.y);
const apply = (state: PlacementState, operation: MoveOperation, history: readonly MoveOperation[], redo: readonly MoveOperation[]): PlacementState => ({ ...state, revision: state.revision + 1, placements: { ...state.placements, [operation.entityId]: { ...state.placements[operation.entityId], entityId: operation.entityId, ...operation.to, pinned: state.placements[operation.entityId]?.pinned ?? false } }, undo: history, redo });
export const MIN_ELEMENT_WIDTH = 120;
export const MIN_ELEMENT_HEIGHT = 72;
export function moveElement(state: PlacementState, entityId: string, to: Point, input: MoveOperation["input"] = "pointer"): PlacementState { if (!entityId || !finite(to)) throw new Error("A valid entity and finite position are required."); const current = state.placements[entityId] ?? { entityId, x: 0, y: 0, pinned: false }; const operation = { entityId, from: { x: current.x, y: current.y }, to, input } as const; return apply(state, operation, [...state.undo, operation], []); }
export const setPinned = (state: PlacementState, entityId: string, pinned: boolean): PlacementState => { const current = state.placements[entityId]; if (!current) return state; return { ...state, revision: state.revision + 1, placements: { ...state.placements, [entityId]: { ...current, pinned } } }; };
export function resizeElement(state: PlacementState, entityId: string, box: Box): PlacementState { if (!entityId || !finite(box) || !Number.isFinite(box.width) || !Number.isFinite(box.height)) throw new Error("A valid entity and finite geometry are required."); const current = state.placements[entityId]; return { ...state, revision: state.revision + 1, placements: { ...state.placements, [entityId]: { ...current, entityId, x: box.x, y: box.y, width: Math.max(MIN_ELEMENT_WIDTH, box.width), height: Math.max(MIN_ELEMENT_HEIGHT, box.height), pinned: true } } }; }
export function undoMove(state: PlacementState): PlacementState { const operation = state.undo.at(-1); if (!operation) return state; return apply(state, { ...operation, from: operation.to, to: operation.from }, state.undo.slice(0, -1), [operation, ...state.redo]); }
export function redoMove(state: PlacementState): PlacementState { const operation = state.redo[0]; if (!operation) return state; return apply(state, operation, [...state.undo, operation], state.redo.slice(1)); }
export function reconcilePlacements(state: PlacementState, entityIds: readonly string[], automatic: Readonly<Record<string, Point>>): PlacementState { const valid = new Set(entityIds); const placements = Object.fromEntries(entityIds.flatMap((id) => { const manual = state.placements[id]; const point = manual?.pinned ? manual : automatic[id] ?? manual; return point && valid.has(id) ? [[id, { ...manual, entityId: id, x: point.x, y: point.y, pinned: manual?.pinned ?? false }]] : []; })); return { ...state, revision: state.revision + 1, placements }; }
